### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jwilson8767** [ORelio/FileActionsManager#1]
@ORelio I know you probably haven't thought about this project in 2 years or so, but I just wanted to write and say thanks for your work on this! I just used FileActionsManager to create a utility over here: https://github.com/jwilson8767/shp2zipwin and it couldn't have been easier!

Thanks!

**Comment by ORelio** [comment]
Hi @jwilson8767
I wrote this app exactly for that purpose and use it every time I reinstall Windows to quickly bring back all my custom context menu items. Glad to hear that it helped someone else 😉
